#   make [test] - builds everything, and runs the tests. just executing "make" will run all tests
#   make build  - just builds everything
# 	make leak 	- runs all test while running address-sanitizer
#   make TARGET - makes the given target.
#   make clean  - removes all files generated by make.

# Project settings. Change these to match your files
.DEFAULT_GOAL := test
HT_IMPL = hash_table
HT_TEST = ht_tests
CXX = g++
CC = gcc
CFLAGS += -g -Wall -std=c11
# Depending on your environment, you may need to include -pthread in your CXXFLAGS
# If you get pthread errors when you run make, try removing the # in the line below
CXXFLAGS += -g -Wall -Wextra -std=c++17 -pthread 

leak : CFLAGS += -fsanitize=address -ggdb 
leak: 	CXXFLAGS= -fsanitize=address -ggdb  
leak: test

# Primary build targets.
test : build
	ASAN_OPTIONS=log_path=stdout ./$(HT_TEST)
# ./$(HT_TEST)

build: $(HT_TEST)

clean :
	rm -f gtest_main.a *.o $(HT_TEST) asan.* *.log

# Targets for building the hash table test suite
$(HT_IMPL).o : $(HT_IMPL).c $(HT_IMPL).h $(GTEST_HEADERS)
	$(CC) $(CFLAGS) -c $(HT_IMPL).c

$(HT_TEST).o : $(HT_TEST).cpp $(HT_IMPL).h $(GTEST_HEADERS)
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $(HT_TEST).cpp

$(HT_TEST) : $(HT_IMPL).o $(HT_TEST).o gtest_main.a
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -lpthread $^ -o $@

# Google test framework settings. Don't mess with these!
GTEST_DIR = gtest
GTEST_HEADERS = $(GTEST_DIR)/include/gtest/*.h \
                $(GTEST_DIR)/include/gtest/internal/*.h
GTEST_SRCS_ = $(GTEST_DIR)/src/*.h $(GTEST_HEADERS)
CPPFLAGS += -isystem $(GTEST_DIR)/include

# Targets for building Google Test framework
gtest-all.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest-all.cc

gtest_main.o : $(GTEST_SRCS_)
	$(CXX) $(CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest_main.cc

gtest_main.a : gtest-all.o gtest_main.o
	$(AR) $(ARFLAGS) $@ $^
